CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  price INTEGER NOT NULL,
  billing_date INTEGER NOT NULL,
  billing_month INTEGER DEFAULT NULL,
  cycle VARCHAR(50) NOT NULL,
  order_index INTEGER DEFAULT 0,
  icon VARCHAR(10) DEFAULT '📦',
  color VARCHAR(20) DEFAULT '#534AB7',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
